language: java

jdk:
- oraclejdk8

env:
- CI=true

before_install:
- cd example/maven-root
- chmod +x gradlew

install:
- ./gradlew assemble --stacktrace --console=plain

script:
- ./gradlew check --stacktrace --console=plain
